repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-json
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.
    - id: check-added-large-files
      args: ['--maxkb=5000']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
    # for windows remove /c//Users//jm//AppData//Roaming//npm//clang-format and keep only *.cmd there!
    -   id: clang-format
        args:
        - --fallback-style=none
        - --style=file
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
    - id: gitleaks
